const HOOKS_BY_STYLE: Record<string, string[]> = {
  default: [
    `I keep seeing {topic} get framed the wrong way.`,
    `The part people miss about {topic} is the workflow.`,
    `{topic} is not about more output. It is about better decisions.`,
    `If you use {topic}, this is the part that matters most.`,
    `Most takes on {topic} skip the hard part.`,
    `The real test of {topic} is whether it saves time.`,
    `What surprised me most about {topic} was the tradeoff.`,
    `There is a better way to think about {topic}.`,
    `{topic} works when it stays close to the builder’s process.`,
    `You do not need hype to explain {topic}.`,
    `{topic} only becomes useful after the third time you touch it.`,
    `Nobody talks about the maintenance cost of {topic}.`,
    `The simplest version of {topic} is usually the one that sticks.`,
    `{topic} does not replace judgment. It exposes it.`,
    `I stopped explaining {topic} and started shipping with it.`,
    `Most people judge {topic} by the demo. The real signal shows up in week two.`,
    `{topic} looks complicated until you trace the actual workflow.`,
    `The best part of {topic} is what it removes from your day.`,
    `{topic} is fine. Your setup around it is the problem.`,
    `Expectations for {topic} are running too far ahead of the practice.`,
    `{topic} stops feeling novel the moment it becomes boring.`,
    `The reason {topic} works is that it reduces decisions, not adds them.`,
    `If {topic} feels noisy, you are probably in the wrong room.`,
    `{topic} works best when you stop optimizing early.`,
    `The real question with {topic} is not whether it works. It is whether you will actually use it.`,
    `{topic} is not magic. It is structure with better defaults.`,
    `What changed my mind about {topic} was the constraint, not the feature.`,
    `Do not build on {topic} because it is trendy. Build on it because it fits your loop.`,
    `{topic} becomes obvious once you remove the things that do not matter.`,
    `The people winning with {topic} are not smarter. They are more consistent.`,
    `{topic}: overcomplicated in docs, simple in practice.`,
    `The failure mode of {topic} is attention, not accuracy.`,
    `{topic} deserves less talk and more long-term use.`,
    `The pattern is simple, but most people miss the first signal.`,
    `{topic} does not care about your opinion. It cares about your process.`,
    `You can tell how serious someone is about {topic} by their constraints, not their claims.`,
    `{topic} is not a strategy. It is a tool that exposes strategy.`,
    `If you only use {topic} once, you will only see the surface.`,
    `{topic} looks easy until you try to make it repeatable.`,
    `The standard for {topic} should be consistency, not perfection.`,
    `{topic}: the boring bet that compounds faster than the exciting one.`,
    `Most advice about {topic} is written by people who stopped using it.`,
    `{topic} is not the future. It is the present that most people ignore.`,
    `The signal in {topic} is quiet until you listen for repetition.`,
    `{topic} only pays off after the novelty wears off.`,
    `The best use of {topic} is not what you think it is.`,
    `{topic} works when you stop expecting it to feel special.`,
    `I have seen more value from boring {topic} habits than from new frameworks.`,
    `The gap with {topic} is not skill. It is follow-through.`,
    `{topic} is not for everyone. It is for the people who show up enough to notice.`,
  ],
  builder: [
    `I build differently because of {topic}.`,
    `{topic} is the missing piece in my daily loop.`,
    `Builders ignore {topic} at their own cost.`,
    `What I like about {topic} is that it respects execution.`,
    `{topic} is not about the idea. It is about the return.`,
    `I use {topic} to ship faster without guessing.`,
    `If you are building, {topic} is not optional.`,
    `{topic} keeps the team focused on what matters.`,
    `The best builders treat {topic} as infrastructure, not entertainment.`,
    `{topic} works because it is boring enough to rely on.`,
    `I replaced a stack of opinions with {topic}.`,
    `{topic} reduced my decision fatigue without reducing quality.`,
    `The thing about {topic} is that it compounds.`,
    `{topic} is the default, not the exception.`,
    `I keep recommending {topic} because it earns trust.`,
    `{topic} is how I turn messy problems into repeatable output.`,
    `Every time I revisit {topic}, I remove more steps.`,
    `{topic} is not a luxury. It is leverage.`,
    `The best product decision I made last quarter was {topic}.`,
    `{topic} works when the team stops debating and starts using it.`,
    `I measure {topic} by how fast we recover from mistakes.`,
    `{topic} is boring. Boring is good.`,
    `The ROI on {topic} is usually six months, not six days.`,
    `{topic} shines when the pressure is high.`,
    `If your process already has gaps, {topic} will expose them fast.`,
    `{topic} is not about perfection. It is about repeatability.`,
    `Winning builders use {topic} to remove noise, not add features.`,
    `The simpler the stack, the more {topic} pays off.`,
    `{topic} becomes the standard once people stop complaining about it.`,
    `I keep coming back to {topic} because it respects time.`,
    `{topic} fails when you treat it as a silver bullet.`,
    `The best signal from {topic} is when it becomes invisible.`,
    `{topic} is the tool I never have to argue for twice.`,
    `If you want velocity, {topic} is the bet.`,
    `{topic} is how I protect the team from context switching.`,
    `The rule is simple: use {topic}, document why, and move on.`,
    `{topic} works when priorities are clear.`,
    `I do not talk about {topic} to look smart. I use it to ship faster.`,
    `{topic} removes the decisions that should have been made months ago.`,
    `The builders who stick with {topic} outlast the hype cycles.`,
    `{topic} is the difference between building and rearranging.`,
    `I trust {topic} more than I trust new frameworks.`,
    `{topic} is the boring infrastructure people thank you for later.`,
    `The more complex the problem, the more {topic} helps.`,
    `{topic} is underrated because it does not make noise.`,
    `If a process is not simple, {topic} will find the cracks.`,
    `{topic} is the quiet advantage in a loud market.`,
    `Builders love {topic} because it respects constraints.`,
    `{topic} makes the team faster by making choices faster.`,
    `{topic} is the stack choice nobody regrets six months later.`,
  ],
  contrarian: [
    `{topic} is overrated if you are not willing to change the workflow that got you here.`,
    `The worst thing you can do is adopt {topic} before fixing the fundamentals.`,
    `{topic} does not matter if you still reward speed over consistency.`,
    `Most people will abandon {topic} once the novelty wears off.`,
    `{topic} is the easy part. The hard part is admitting it will not fix everything.`,
    `If {topic} is your entire strategy, your strategy is weak.`,
    `{topic} is fine until it becomes your identity.`,
    `The hype around {topic} exceeds the evidence by a lot.`,
    `{topic} works for a small group. Stop pretending it works for everyone.`,
    `{topic} is not the answer. It is a clue.`,
    `{topic} sounds smart in threads. It looks weak in production.`,
    `The people pushing {topic} hardest are usually selling something else.`,
    `{topic} is the new version of last year's favorite tool.`,
    `Let go of {topic} if it costs you more than it returns.`,
    `{topic} is popular because it feels productive, not because it is productive.`,
    `You do not need {topic}. You need discipline.`,
    `{topic} will not survive your first bad week.`,
    `Talking about {topic} is easier than using it well.`,
    `{topic} is not a moat. Execution is.`,
    `Most teams will fail with {topic} because they expect it to do the thinking.`,
    `{topic} is less interesting than the problems it pretends to solve.`,
    `{topic} is only revolutionary if you ignore the last decade of the same pattern.`,
    `If {topic} were that powerful, everyone would already be winning with it.`,
    `{topic} highlights the gap between shiny demos and real output.`,
    `{topic} is a tool, not a talent.`,
    `The real test is not whether {topic} is good. It is whether you stop using it when it is not.`,
    `{topic} works until reality shows up.`,
    `Nobody wins by optimizing {topic}. They win by shipping.`,
    `{topic} is not worth the migration cost unless your current process is already broken.`,
    `The danger of {topic} is how good it feels before it delivers.`,
    `{topic} is the new resume-driven development.`,
    `If {topic} is the answer, you are asking the wrong question.`,
    `{topic} will be forgotten before the bugs are fixed.`,
    `Be honest: {topic} is mostly a distraction from hard calls.`,
    `{topic}: great for posts, underwhelming for products.`,
    `{topic} is not different enough to justify switching now.`,
    `The best take on {topic} is a quiet one.`,
    `{topic} sounds impressive until you ask for evidence.`,
    `Do not let {topic} distract you from what already works.`,
    `{topic} solves problems you do not have if you are not careful.`,
    `{topic} is interesting. That is not the same as useful.`,
    `{topic}: good enough for a demo, not good enough for a deadline.`,
    `The market will correct the {topic} hype. You can either ride it or ignore it.`,
    `Adopting {topic} late is usually smarter than adopting it early.`,
    `{topic} is only impressive when the results last longer than the buzz.`,
    `Weak teams use {topic} to look busy. Strong teams use it to remove friction.`,
    `{topic} will not fix a market that does not want your product.`,
    `The safest bet with {topic} is to wait until the noise settles.`,
    `{topic} is over once people stop posting about it.`,
  ],
  educational: [
    `Key thing about {topic}: start with the problem, not the tool.`,
    `{topic} explained in one line: reduce complexity, keep control.`,
    `If you want to understand {topic}, trace the full workflow first.`,
    `The biggest misconception about {topic} is that it replaces skill.`,
    `{topic} works because it enforces a tighter loop between input and feedback.`,
    `To learn {topic}, use it on a real task, not a tutorial.`,
    `{topic} 101: the goal is repeatability, not cleverness.`,
    `Most guides oversell {topic}. The reality is simpler and more useful.`,
    `The secret to {topic} is constraints. Add more, not less.`,
    `{topic} works when you measure before and after.`,
    `Start with {topic} by removing one tool first.`,
    `The difference between using {topic} and mastering it is feedback loops.`,
    `{topic} is best learned by breaking it and fixing it.`,
    `Understanding {topic} starts with understanding what it does not do.`,
    `{topic} becomes clear once you map the steps it removes.`,
    `Good {topic} setups are quiet, not flashy.`,
    `Do not confuse {topic} complexity with {topic} value.`,
    `Before adopting {topic}, list what you expect it to replace.`,
    `{topic} is a system. If you only use pieces, you miss the advantage.`,
    `Teach {topic} with examples, not terminology.`,
    `The myth: {topic} requires expertise. The truth: it teaches attention.`,
    `{topic}: one workflow at a time, then expand.`,
    `Measureful learning in {topic} means logging outcomes, not hours.`,
    `The best explanation of {topic} is a before-and-after workflow.`,
    `{topic} works best with explicit rules and repeatable steps.`,
    `If {topic} feels random, your process is missing structure.`,
    `I explain {topic} by showing what disappears when it is done right.`,
    `{topic} is easier to evaluate than to sell.`,
    `The correct order: workflow first, {topic} second.`,
    `Do not optimize {topic} until you know which step is slow.`,
    `{topic}: useful when you stop trying to impress people with it.`,
    `The first step to {topic} is defining the loop, not the tool.`,
    `{topic} reduces noise. Keep the useful noise.`,
    `Use {topic} to find bottlenecks. That is its real job.`,
    `{topic} is misunderstood because people copy the output and skip the process.`,
    `The honest intro to {topic} is boring but effective.`,
    `{topic}: practice beats theory by a mile.`,
    `Good {topic} habits beat fancy {topic} setups.`,
    `{topic} is learned in small, repeated tasks.`,
    `The fastest way to {topic} is to remove unnecessary steps first.`,
    `{topic} is only hard when you ignore the existing workflow.`,
    `Focus on {topic} output, not input.`,
    `The best {topic} tutorial is a working workflow.`,
    `{topic}: you are probably overcomplicating the core idea.`,
    `Real {topic} skill shows up in consistency, not configuration.`,
    `If {topic} feels complicated, simplify the inputs.`,
    `{topic} becomes elegant when constraints are enforced first.`,
    `Master {topic} by measuring, repeating, and removing.`,
    `{topic} is a practice problem that never ends.`,
    `The simplest explanation of {topic} is the one that survives real use.`,
  ],
  story: [
    `Last week, {topic} changed how I finished a project on deadline.`,
    `I thought {topic} was hype until a broken process forced me to use it.`,
    `The moment I trusted {topic} was the moment I stopped micromanaging the output.`,
    `{topic} saved me when a client deadline collided with bad data.`,
    `I used {topic} to turn a chaotic week into a repeatable routine.`,
    `The turning point with {topic} was realizing my process was the real bottleneck.`,
    `{topic} showed up when nothing else did.`,
    `I learned {topic} from a builder who had already shipped three products.`,
    `The story of {topic} in my workflow is the story of fewer mistakes.`,
    `{topic} feels like magic until you see the constraints behind it.`,
    `I did not adopt {topic} because of a tweet. I adopted it after failing without it.`,
    `{topic} is the plot twist that made a project survive.`,
    `The problem looked like a technology problem. It was actually a {topic} problem.`,
    `{topic} became my answer after three failed workflows.`,
    `I used {topic} to recover from a decision I made too fast.`,
    `The lesson from {topic} is that the right constraint beats the right idea.`,
    `{topic} works because it came from a week where nothing else worked.`,
    `What made {topic} click was removing the options that did not fit.`,
    `{topic} changed the story from tight deadlines to steady output.`,
    `If you want a story about {topic}, start with a broken process.`,
    `The buildup to {topic} was failure, not curiosity.`,
    `{topic} showed its value on a weekend when nothing else was moving.`,
    `I measure {topic} by the mornings it saved me from replanning.`,
    `The first clue that {topic} was real was silence. No more noise.`,
    `{topic} is the story of choosing consistency over cleverness.`,
    `I was skeptical of {topic} until it replaced my whole daily ritual.`,
    `{topic} taught me that good defaults are worth more than great ideas.`,
    `The story: from scattered tools to {topic} in thirty days.`,
    `{topic} earned its place when it handled a case no human wanted to touch again.`,
    `The best {topic} moment is when you stop calling it a tool and call it the process.`,
    `{topic} made the ugly edge case disappear.`,
    `Before {topic}, every launch felt improvised. After, it felt repeatable.`,
    `The reason {topic} stuck is because it showed results before I finished explaining it.`,
    `{topic} is the breakthrough that came from constraint, not inspiration.`,
    `I share {topic} because I have lived the alternative and it is painful.`,
    `{topic} became compelling when it turned chaos into one loop.`,
    `The story of {topic}: three failed attempts, one quiet win.`,
    `{topic} is what I use when I have to ship without explaining myself.`,
    `The moment that sold {topic} was a Friday evening release that did not fail.`,
    `{topic}: the tool I did not want to use, but could not ignore.`,
    `If {topic} had a face, it would look like a saved day.`,
    `{topic} changed my story from reactive to prepared.`,
    `The narrative shifted when {topic} turned an accident into a habit.`,
    `{topic} became the story because the old way was no longer a story worth telling.`,
    `I talk about {topic} because it is the difference between a project and a process.`,
    `{topic} is most convincing when you do not have to explain it at all.`,
    `{topic}: the chapter where I stopped improvising and started standardizing.`,
    `The turning point was when {topic} made the hard decision first.`,
    `{topic} works because it respects the builder’s time and attention.`,
    `{topic} is the quiet chapter in the story of doing more with less.`,
  ],
  technical: [
    `{topic} reduces risk by shrinking the number of moving parts.`,
    `With {topic}, you trade configuration flexibility for operational simplicity.`,
    `The architecture behind {topic} relies on tight feedback loops.`,
    `{topic} works by enforcing deterministic rules over arbitrary decisions.`,
    `The default behavior of {topic} is conservative by design.`,
    `{topic}: lower surface area means faster troubleshooting.`,
    `Internally, {topic} isolates state and updates it in small steps.`,
    `{topic} is most valuable when your pipeline already has reliable anchors.`,
    `Using {topic} means fewer conditional branches in your workflow.`,
    `{topic} behaves predictably because it simplifies the interface, not the output.`,
    `Scaling {topic} means scaling discipline, not components.`,
    `{topic} is a solid choice when latency and control matter more than novelty.`,
    `{topic} follows a narrow contract: take input, apply rules, return output.`,
    `The implementation of {topic} favors consistency over configurability.`,
    `{topic} reduces coupling between steps, which improves maintainability.`,
    `With {topic}, you replace decision-heavy workflows with rule-driven ones.`,
    `{topic} defaults to local state because shared state is expensive.`,
    `{topic} is easy to audit because it leaves a clean trail of transformations.`,
    `The ideal use case for {topic} is repeatable, constraint-driven work.`,
    `{topic} becomes a force multiplier once you stabilize the upstream inputs.`,
    `{topic}: small surface, clear semantics, predictable behavior.`,
    `In practice, {topic} decreases variance without decreasing visibility.`,
    `{topic} keeps the pipeline lean by removing choice at the right layer.`,
    `The mental model for {topic} is simpler than most alternatives.`,
    `{topic} encourages single-responsibility steps instead of combined workflows.`,
    `Error cases in {topic} are easier to trace because the logic is explicit.`,
    `{topic} works well with local-first systems because it avoids shared-state coupling.`,
    `The contract of {topic} is small enough to reason about end to end.`,
    `{topic} is reliable because it minimizes runtime decisions.`,
    `{topic}: predictable output from deterministic inputs.`,
    `{topic} is most effective after the schema is stable.`,
    `{topic} trades broad flexibility for targeted consistency.`,
    `With {topic}, the trace from input to output is always auditable.`,
    `{topic} is conservative by nature, which is a feature under load.`,
    `The data flow of {topic} is simpler than most modern alternatives.`,
    `{topic} makes pipelines easier to test by reducing branching logic.`,
    `A good {topic} setup has one clear rule per transformation.`,
    `{topic} prioritizes simplicity over feature richness, which pays off at scale.`,
    `{topic}: less abstraction, more control.`,
    `The technical benefit of {topic} is faster debugging, not faster shipping.`,
    `{topic} avoids shared state to reduce race conditions in long workflows.`,
    `{topic}: local, rule-based, and easy to inspect.`,
    `With {topic}, you can reason about failures in minutes instead of hours.`,
    `{topic} is designed to fail loudly, not silently.`,
    `The simplest system wins: {topic} follows that principle.`,
    `{topic} is a technical bet on simplicity over flexibility.`,
    `{topic} reduces cognitive load by removing options.`,
    `The pipeline wins when {topic} handles the repetitive steps faithfully.`,
    `{topic} is a pattern that scales with constraints, not complexity.`,
    `For local-first systems, {topic} is a natural fit.`,
  ],
};

export type HookStyle = keyof typeof HOOKS_BY_STYLE;
export const HOOK_STYLES: HookStyle[] = Object.keys(HOOKS_BY_STYLE) as HookStyle[];

export function generateHooks(topic: string, count = 10, style: HookStyle = 'default') {
  const cleaned = topic.trim();
  if (!cleaned) return [];
  const safeCount = Math.min(50, Math.max(1, count));
  const templates = HOOKS_BY_STYLE[style] || HOOKS_BY_STYLE.default;
  const hooks = [];
  for (let i = 0; i < safeCount; i++) {
    hooks.push(templates[i % templates.length].replace(/\{topic\}/g, cleaned));
  }
  return hooks;
}
